// -----------------------------------------------------------------------------
// File      : bus_top.v
// Brief     : Auto-generated by autowire.py v2.0
// Author    : czz
// Date      : 2025-09-13 12:30:30
// -----------------------------------------------------------------------------

module bus_top(
    // u_DW_axi_x2x ports
    input           aclk,
    input           aresetn,
    input           awvalid_m1,
    input   [31:0]  awaddr_m1,
    input   [3:0]   awid_m1,
    input   [7:0]   awlen_m1,
    input   [2:0]   awsize_m1,
    input   [1:0]   awburst_m1,
    input   [1:0]   awlock_m1,
    input   [3:0]   awcache_m1,
    input   [2:0]   awprot_m1,
    output          awready_m1,
    input           wvalid_m1,
    input   [3:0]   wid_m1,
    input   [31:0]  wdata_m1,
    input   [3:0]   wstrb_m1,
    input           wlast_m1,
    output          wready_m1,
    output          bvalid_m1,
    output  [3:0]   bid_m1,
    output  [1:0]   bresp_m1,
    input           bready_m1,
    input           arvalid_m1,
    input   [3:0]   arid_m1,
    input   [31:0]  araddr_m1,
    input   [7:0]   arlen_m1,
    input   [2:0]   arsize_m1,
    input   [1:0]   arburst_m1,
    input   [1:0]   arlock_m1,
    input   [3:0]   arcache_m1,
    input   [2:0]   arprot_m1,
    output          arready_m1,
    output          rvalid_m1,
    output  [3:0]   rid_m1,
    output  [31:0]  rdata_m1,
    output          rlast_m1,
    output  [1:0]   rresp_m1,
    input           rready_m1,

    // u_DW_axi ports
    input           awvalid_m2,
    input   [31:0]  awaddr_m2,
    input   [3:0]   awid_m2,
    input   [7:0]   awlen_m2,
    input   [2:0]   awsize_m2,
    input   [1:0]   awburst_m2,
    input           awlock_m2,
    input   [3:0]   awcache_m2,
    input   [2:0]   awprot_m2,
    output          awready_m2,
    input           wvalid_m2,
    input   [63:0]  wdata_m2,
    input   [7:0]   wstrb_m2,
    input           wlast_m2,
    output          wready_m2,
    output          bvalid_m2,
    output  [3:0]   bid_m2,
    output  [1:0]   bresp_m2,
    input           bready_m2,
    input           arvalid_m2,
    input   [3:0]   arid_m2,
    input   [31:0]  araddr_m2,
    input   [7:0]   arlen_m2,
    input   [2:0]   arsize_m2,
    input   [1:0]   arburst_m2,
    input           arlock_m2,
    input   [3:0]   arcache_m2,
    input   [2:0]   arprot_m2,
    output          arready_m2,
    output          rvalid_m2,
    output  [3:0]   rid_m2,
    output  [63:0]  rdata_m2,
    output          rlast_m2,
    output  [1:0]   rresp_m2,
    input           rready_m2,
    input           awvalid_m3,
    input   [31:0]  awaddr_m3,
    input   [3:0]   awid_m3,
    input   [7:0]   awlen_m3,
    input   [2:0]   awsize_m3,
    input   [1:0]   awburst_m3,
    input           awlock_m3,
    input   [3:0]   awcache_m3,
    input   [2:0]   awprot_m3,
    output          awready_m3,
    input           wvalid_m3,
    input   [63:0]  wdata_m3,
    input   [7:0]   wstrb_m3,
    input           wlast_m3,
    output          wready_m3,
    output          bvalid_m3,
    output  [3:0]   bid_m3,
    output  [1:0]   bresp_m3,
    input           bready_m3,
    input           arvalid_m3,
    input   [3:0]   arid_m3,
    input   [31:0]  araddr_m3,
    input   [7:0]   arlen_m3,
    input   [2:0]   arsize_m3,
    input   [1:0]   arburst_m3,
    input           arlock_m3,
    input   [3:0]   arcache_m3,
    input   [2:0]   arprot_m3,
    output          arready_m3,
    output          rvalid_m3,
    output  [3:0]   rid_m3,
    output  [63:0]  rdata_m3,
    output          rlast_m3,
    output  [1:0]   rresp_m3,
    input           rready_m3,
    output          awvalid_s1,
    output  [31:0]  awaddr_s1,
    output  [5:0]   awid_s1,
    output  [7:0]   awlen_s1,
    output  [2:0]   awsize_s1,
    output  [1:0]   awburst_s1,
    output          awlock_s1,
    output  [3:0]   awcache_s1,
    output  [2:0]   awprot_s1,
    input           awready_s1,
    output          wvalid_s1,
    output  [63:0]  wdata_s1,
    output  [7:0]   wstrb_s1,
    output          wlast_s1,
    input           wready_s1,
    input           bvalid_s1,
    input   [5:0]   bid_s1,
    input   [1:0]   bresp_s1,
    output          bready_s1,
    output          arvalid_s1,
    output  [5:0]   arid_s1,
    output  [31:0]  araddr_s1,
    output  [7:0]   arlen_s1,
    output  [2:0]   arsize_s1,
    output  [1:0]   arburst_s1,
    output          arlock_s1,
    output  [3:0]   arcache_s1,
    output  [2:0]   arprot_s1,
    input           arready_s1,
    input           rvalid_s1,
    input   [5:0]   rid_s1,
    input   [63:0]  rdata_s1,
    input           rlast_s1,
    input   [1:0]   rresp_s1,
    output          rready_s1,
    output          awvalid_s2,
    output  [31:0]  awaddr_s2,
    output  [5:0]   awid_s2,
    output  [7:0]   awlen_s2,
    output  [2:0]   awsize_s2,
    output  [1:0]   awburst_s2,
    output          awlock_s2,
    output  [3:0]   awcache_s2,
    output  [2:0]   awprot_s2,
    input           awready_s2,
    output          wvalid_s2,
    output  [63:0]  wdata_s2,
    output  [7:0]   wstrb_s2,
    output          wlast_s2,
    input           wready_s2,
    input           bvalid_s2,
    input   [5:0]   bid_s2,
    input   [1:0]   bresp_s2,
    output          bready_s2,
    output          arvalid_s2,
    output  [5:0]   arid_s2,
    output  [31:0]  araddr_s2,
    output  [7:0]   arlen_s2,
    output  [2:0]   arsize_s2,
    output  [1:0]   arburst_s2,
    output          arlock_s2,
    output  [3:0]   arcache_s2,
    output  [2:0]   arprot_s2,
    input           arready_s2,
    input           rvalid_s2,
    input   [5:0]   rid_s2,
    input   [63:0]  rdata_s2,
    input           rlast_s2,
    input   [1:0]   rresp_s2,
    output          rready_s2
);

wire  [31:0]  araddr_m1_conv ;
wire  [1:0]   arburst_m1_conv;
wire  [3:0]   arcache_m1_conv;
wire  [3:0]   arid_m1_conv   ;
wire  [7:0]   arlen_m1_conv  ;
wire  [1:0]   arlock_m1_conv ;
wire  [2:0]   arprot_m1_conv ;
wire          arready_m1_conv;
wire  [2:0]   arsize_m1_conv ;
wire          arvalid_m1_conv;
wire  [31:0]  awaddr_m1_conv ;
wire  [1:0]   awburst_m1_conv;
wire  [3:0]   awcache_m1_conv;
wire  [3:0]   awid_m1_conv   ;
wire  [7:0]   awlen_m1_conv  ;
wire  [1:0]   awlock_m1_conv ;
wire  [2:0]   awprot_m1_conv ;
wire          awready_m1_conv;
wire  [2:0]   awsize_m1_conv ;
wire          awvalid_m1_conv;
wire  [3:0]   bid_m1_conv    ;
wire          bready_m1_conv ;
wire  [1:0]   bresp_m1_conv  ;
wire          bvalid_m1_conv ;
wire  [63:0]  rdata_m1_conv  ;
wire  [3:0]   rid_m1_conv    ;
wire          rlast_m1_conv  ;
wire          rready_m1_conv ;
wire  [1:0]   rresp_m1_conv  ;
wire          rvalid_m1_conv ;
wire  [63:0]  wdata_m1_conv  ;
wire          wlast_m1_conv  ;
wire          wready_m1_conv ;
wire  [7:0]   wstrb_m1_conv  ;
wire          wvalid_m1_conv ;

// Instance: u_DW_axi_x2x (DW_axi_x2x)
DW_axi_x2x u_DW_axi_x2x (
    .aclk_m         (aclk             ),    // input 
    .aresetn_m      (aresetn          ),    // input 
    .awvalid_m      (awvalid_m1       ),    // input 
    .awaddr_m       (awaddr_m1        ),    // input  [31:0]
    .awid_m         (awid_m1          ),    // input  [3:0]
    .awlen_m        (awlen_m1         ),    // input  [7:0]
    .awsize_m       (awsize_m1        ),    // input  [2:0]
    .awburst_m      (awburst_m1       ),    // input  [1:0]
    .awlock_m       (awlock_m1        ),    // input  [1:0]
    .awcache_m      (awcache_m1       ),    // input  [3:0]
    .awprot_m       (awprot_m1        ),    // input  [2:0]
    .awready_m      (awready_m1       ),    // output
    .wvalid_m       (wvalid_m1        ),    // input 
    .wid_m          (wid_m1           ),    // input  [3:0]
    .wdata_m        (wdata_m1         ),    // input  [31:0]
    .wstrb_m        (wstrb_m1         ),    // input  [3:0]
    .wlast_m        (wlast_m1         ),    // input 
    .wready_m       (wready_m1        ),    // output
    .bvalid_m       (bvalid_m1        ),    // output
    .bid_m          (bid_m1           ),    // output [3:0]
    .bresp_m        (bresp_m1         ),    // output [1:0]
    .bready_m       (bready_m1        ),    // input 
    .arvalid_m      (arvalid_m1       ),    // input 
    .arid_m         (arid_m1          ),    // input  [3:0]
    .araddr_m       (araddr_m1        ),    // input  [31:0]
    .arlen_m        (arlen_m1         ),    // input  [7:0]
    .arsize_m       (arsize_m1        ),    // input  [2:0]
    .arburst_m      (arburst_m1       ),    // input  [1:0]
    .arlock_m       (arlock_m1        ),    // input  [1:0]
    .arcache_m      (arcache_m1       ),    // input  [3:0]
    .arprot_m       (arprot_m1        ),    // input  [2:0]
    .arready_m      (arready_m1       ),    // output
    .rvalid_m       (rvalid_m1        ),    // output
    .rid_m          (rid_m1           ),    // output [3:0]
    .rdata_m        (rdata_m1         ),    // output [31:0]
    .rlast_m        (rlast_m1         ),    // output
    .rresp_m        (rresp_m1         ),    // output [1:0]
    .rready_m       (rready_m1        ),    // input 
    .awvalid_s1     (awvalid_m1_conv  ),    // output
    .awaddr_s1      (awaddr_m1_conv   ),    // output [31:0]
    .awid_s1        (awid_m1_conv     ),    // output [3:0]
    .awlen_s1       (awlen_m1_conv    ),    // output [7:0]
    .awsize_s1      (awsize_m1_conv   ),    // output [2:0]
    .awburst_s1     (awburst_m1_conv  ),    // output [1:0]
    .awlock_s1      (awlock_m1_conv   ),    // output [1:0]
    .awcache_s1     (awcache_m1_conv  ),    // output [3:0]
    .awprot_s1      (awprot_m1_conv   ),    // output [2:0]
    .awready_s1     (awready_m1_conv  ),    // input 
    .wvalid_s1      (wvalid_m1_conv   ),    // output
    .wid_s1         (                 ),    // output [3:0]
    .wdata_s1       (wdata_m1_conv    ),    // output [63:0]
    .wstrb_s1       (wstrb_m1_conv    ),    // output [7:0]
    .wlast_s1       (wlast_m1_conv    ),    // output
    .wready_s1      (wready_m1_conv   ),    // input 
    .bvalid_s1      (bvalid_m1_conv   ),    // input 
    .bid_s1         (bid_m1_conv      ),    // input  [3:0]
    .bresp_s1       (bresp_m1_conv    ),    // input  [1:0]
    .bready_s1      (bready_m1_conv   ),    // output
    .arvalid_s      (arvalid_m1_conv  ),    // output
    .arid_s         (arid_m1_conv     ),    // output [3:0]
    .araddr_s       (araddr_m1_conv   ),    // output [31:0]
    .arlen_s        (arlen_m1_conv    ),    // output [7:0]
    .arsize_s       (arsize_m1_conv   ),    // output [2:0]
    .arburst_s      (arburst_m1_conv  ),    // output [1:0]
    .arlock_s       (arlock_m1_conv   ),    // output [1:0]
    .arcache_s      (arcache_m1_conv  ),    // output [3:0]
    .arprot_s       (arprot_m1_conv   ),    // output [2:0]
    .arready_s      (arready_m1_conv  ),    // input 
    .rvalid_s       (rvalid_m1_conv   ),    // input 
    .rid_s          (rid_m1_conv      ),    // input  [3:0]
    .rdata_s        (rdata_m1_conv    ),    // input  [63:0]
    .rlast_s        (rlast_m1_conv    ),    // input 
    .rresp_s        (rresp_m1_conv    ),    // input  [1:0]
    .rready_s       (rready_m1_conv   )     // output
);

// Instance: u_DW_axi (DW_axi)
DW_axi u_DW_axi (
    .aclk           (aclk             ),    // input 
    .aresetn        (aresetn          ),    // input 
    .awvalid_m1     (awvalid_m1_conv  ),    // input 
    .awaddr_m1      (awaddr_m1_conv   ),    // input  [31:0]
    .awid_m1        (awid_m1_conv     ),    // input  [3:0]
    .awlen_m1       (awlen_m1_conv    ),    // input  [7:0]
    .awsize_m1      (awsize_m1_conv   ),    // input  [2:0]
    .awburst_m1     (awburst_m1_conv  ),    // input  [1:0]
    .awlock_m1      (awlock_m1_conv[0]),    // input 
    .awcache_m1     (awcache_m1_conv  ),    // input  [3:0]
    .awprot_m1      (awprot_m1_conv   ),    // input  [2:0]
    .awready_m1     (awready_m1_conv  ),    // output
    .wvalid_m1      (wvalid_m1_conv   ),    // input 
    .wdata_m1       (wdata_m1_conv    ),    // input  [63:0]
    .wstrb_m1       (wstrb_m1_conv    ),    // input  [7:0]
    .wlast_m1       (wlast_m1_conv    ),    // input 
    .wready_m1      (wready_m1_conv   ),    // output
    .bvalid_m1      (bvalid_m1_conv   ),    // output
    .bid_m1         (bid_m1_conv      ),    // output [3:0]
    .bresp_m1       (bresp_m1_conv    ),    // output [1:0]
    .bready_m1      (bready_m1_conv   ),    // input 
    .arvalid_m1     (arvalid_m1_conv  ),    // input 
    .arid_m1        (arid_m1_conv     ),    // input  [3:0]
    .araddr_m1      (araddr_m1_conv   ),    // input  [31:0]
    .arlen_m1       (arlen_m1_conv    ),    // input  [7:0]
    .arsize_m1      (arsize_m1_conv   ),    // input  [2:0]
    .arburst_m1     (arburst_m1_conv  ),    // input  [1:0]
    .arlock_m1      (arlock_m1_conv[0]),    // input 
    .arcache_m1     (arcache_m1_conv  ),    // input  [3:0]
    .arprot_m1      (arprot_m1_conv   ),    // input  [2:0]
    .arready_m1     (arready_m1_conv  ),    // output
    .rvalid_m1      (rvalid_m1_conv   ),    // output
    .rid_m1         (rid_m1_conv      ),    // output [3:0]
    .rdata_m1       (rdata_m1_conv    ),    // output [63:0]
    .rlast_m1       (rlast_m1_conv    ),    // output
    .rresp_m1       (rresp_m1_conv    ),    // output [1:0]
    .rready_m1      (rready_m1_conv   ),    // input 
    .awvalid_m2     (awvalid_m2       ),    // input 
    .awaddr_m2      (awaddr_m2        ),    // input  [31:0]
    .awid_m2        (awid_m2          ),    // input  [3:0]
    .awlen_m2       (awlen_m2         ),    // input  [7:0]
    .awsize_m2      (awsize_m2        ),    // input  [2:0]
    .awburst_m2     (awburst_m2       ),    // input  [1:0]
    .awlock_m2      (awlock_m2        ),    // input 
    .awcache_m2     (awcache_m2       ),    // input  [3:0]
    .awprot_m2      (awprot_m2        ),    // input  [2:0]
    .awready_m2     (awready_m2       ),    // output
    .wvalid_m2      (wvalid_m2        ),    // input 
    .wdata_m2       (wdata_m2         ),    // input  [63:0]
    .wstrb_m2       (wstrb_m2         ),    // input  [7:0]
    .wlast_m2       (wlast_m2         ),    // input 
    .wready_m2      (wready_m2        ),    // output
    .bvalid_m2      (bvalid_m2        ),    // output
    .bid_m2         (bid_m2           ),    // output [3:0]
    .bresp_m2       (bresp_m2         ),    // output [1:0]
    .bready_m2      (bready_m2        ),    // input 
    .arvalid_m2     (arvalid_m2       ),    // input 
    .arid_m2        (arid_m2          ),    // input  [3:0]
    .araddr_m2      (araddr_m2        ),    // input  [31:0]
    .arlen_m2       (arlen_m2         ),    // input  [7:0]
    .arsize_m2      (arsize_m2        ),    // input  [2:0]
    .arburst_m2     (arburst_m2       ),    // input  [1:0]
    .arlock_m2      (arlock_m2        ),    // input 
    .arcache_m2     (arcache_m2       ),    // input  [3:0]
    .arprot_m2      (arprot_m2        ),    // input  [2:0]
    .arready_m2     (arready_m2       ),    // output
    .rvalid_m2      (rvalid_m2        ),    // output
    .rid_m2         (rid_m2           ),    // output [3:0]
    .rdata_m2       (rdata_m2         ),    // output [63:0]
    .rlast_m2       (rlast_m2         ),    // output
    .rresp_m2       (rresp_m2         ),    // output [1:0]
    .rready_m2      (rready_m2        ),    // input 
    .awvalid_m3     (awvalid_m3       ),    // input 
    .awaddr_m3      (awaddr_m3        ),    // input  [31:0]
    .awid_m3        (awid_m3          ),    // input  [3:0]
    .awlen_m3       (awlen_m3         ),    // input  [7:0]
    .awsize_m3      (awsize_m3        ),    // input  [2:0]
    .awburst_m3     (awburst_m3       ),    // input  [1:0]
    .awlock_m3      (awlock_m3        ),    // input 
    .awcache_m3     (awcache_m3       ),    // input  [3:0]
    .awprot_m3      (awprot_m3        ),    // input  [2:0]
    .awready_m3     (awready_m3       ),    // output
    .wvalid_m3      (wvalid_m3        ),    // input 
    .wdata_m3       (wdata_m3         ),    // input  [63:0]
    .wstrb_m3       (wstrb_m3         ),    // input  [7:0]
    .wlast_m3       (wlast_m3         ),    // input 
    .wready_m3      (wready_m3        ),    // output
    .bvalid_m3      (bvalid_m3        ),    // output
    .bid_m3         (bid_m3           ),    // output [3:0]
    .bresp_m3       (bresp_m3         ),    // output [1:0]
    .bready_m3      (bready_m3        ),    // input 
    .arvalid_m3     (arvalid_m3       ),    // input 
    .arid_m3        (arid_m3          ),    // input  [3:0]
    .araddr_m3      (araddr_m3        ),    // input  [31:0]
    .arlen_m3       (arlen_m3         ),    // input  [7:0]
    .arsize_m3      (arsize_m3        ),    // input  [2:0]
    .arburst_m3     (arburst_m3       ),    // input  [1:0]
    .arlock_m3      (arlock_m3        ),    // input 
    .arcache_m3     (arcache_m3       ),    // input  [3:0]
    .arprot_m3      (arprot_m3        ),    // input  [2:0]
    .arready_m3     (arready_m3       ),    // output
    .rvalid_m3      (rvalid_m3        ),    // output
    .rid_m3         (rid_m3           ),    // output [3:0]
    .rdata_m3       (rdata_m3         ),    // output [63:0]
    .rlast_m3       (rlast_m3         ),    // output
    .rresp_m3       (rresp_m3         ),    // output [1:0]
    .rready_m3      (rready_m3        ),    // input 
    .awvalid_s1     (awvalid_s1       ),    // output
    .awaddr_s1      (awaddr_s1        ),    // output [31:0]
    .awid_s1        (awid_s1          ),    // output [5:0]
    .awlen_s1       (awlen_s1         ),    // output [7:0]
    .awsize_s1      (awsize_s1        ),    // output [2:0]
    .awburst_s1     (awburst_s1       ),    // output [1:0]
    .awlock_s1      (awlock_s1        ),    // output
    .awcache_s1     (awcache_s1       ),    // output [3:0]
    .awprot_s1      (awprot_s1        ),    // output [2:0]
    .awready_s1     (awready_s1       ),    // input 
    .wvalid_s1      (wvalid_s1        ),    // output
    .wdata_s1       (wdata_s1         ),    // output [63:0]
    .wstrb_s1       (wstrb_s1         ),    // output [7:0]
    .wlast_s1       (wlast_s1         ),    // output
    .wready_s1      (wready_s1        ),    // input 
    .bvalid_s1      (bvalid_s1        ),    // input 
    .bid_s1         (bid_s1           ),    // input  [5:0]
    .bresp_s1       (bresp_s1         ),    // input  [1:0]
    .bready_s1      (bready_s1        ),    // output
    .arvalid_s1     (arvalid_s1       ),    // output
    .arid_s1        (arid_s1          ),    // output [5:0]
    .araddr_s1      (araddr_s1        ),    // output [31:0]
    .arlen_s1       (arlen_s1         ),    // output [7:0]
    .arsize_s1      (arsize_s1        ),    // output [2:0]
    .arburst_s1     (arburst_s1       ),    // output [1:0]
    .arlock_s1      (arlock_s1        ),    // output
    .arcache_s1     (arcache_s1       ),    // output [3:0]
    .arprot_s1      (arprot_s1        ),    // output [2:0]
    .arready_s1     (arready_s1       ),    // input 
    .rvalid_s1      (rvalid_s1        ),    // input 
    .rid_s1         (rid_s1           ),    // input  [5:0]
    .rdata_s1       (rdata_s1         ),    // input  [63:0]
    .rlast_s1       (rlast_s1         ),    // input 
    .rresp_s1       (rresp_s1         ),    // input  [1:0]
    .rready_s1      (rready_s1        ),    // output
    .awvalid_s2     (awvalid_s2       ),    // output
    .awaddr_s2      (awaddr_s2        ),    // output [31:0]
    .awid_s2        (awid_s2          ),    // output [5:0]
    .awlen_s2       (awlen_s2         ),    // output [7:0]
    .awsize_s2      (awsize_s2        ),    // output [2:0]
    .awburst_s2     (awburst_s2       ),    // output [1:0]
    .awlock_s2      (awlock_s2        ),    // output
    .awcache_s2     (awcache_s2       ),    // output [3:0]
    .awprot_s2      (awprot_s2        ),    // output [2:0]
    .awready_s2     (awready_s2       ),    // input 
    .wvalid_s2      (wvalid_s2        ),    // output
    .wdata_s2       (wdata_s2         ),    // output [63:0]
    .wstrb_s2       (wstrb_s2         ),    // output [7:0]
    .wlast_s2       (wlast_s2         ),    // output
    .wready_s2      (wready_s2        ),    // input 
    .bvalid_s2      (bvalid_s2        ),    // input 
    .bid_s2         (bid_s2           ),    // input  [5:0]
    .bresp_s2       (bresp_s2         ),    // input  [1:0]
    .bready_s2      (bready_s2        ),    // output
    .arvalid_s2     (arvalid_s2       ),    // output
    .arid_s2        (arid_s2          ),    // output [5:0]
    .araddr_s2      (araddr_s2        ),    // output [31:0]
    .arlen_s2       (arlen_s2         ),    // output [7:0]
    .arsize_s2      (arsize_s2        ),    // output [2:0]
    .arburst_s2     (arburst_s2       ),    // output [1:0]
    .arlock_s2      (arlock_s2        ),    // output
    .arcache_s2     (arcache_s2       ),    // output [3:0]
    .arprot_s2      (arprot_s2        ),    // output [2:0]
    .arready_s2     (arready_s2       ),    // input 
    .rvalid_s2      (rvalid_s2        ),    // input 
    .rid_s2         (rid_s2           ),    // input  [5:0]
    .rdata_s2       (rdata_s2         ),    // input  [63:0]
    .rlast_s2       (rlast_s2         ),    // input 
    .rresp_s2       (rresp_s2         ),    // input  [1:0]
    .rready_s2      (rready_s2        ),    // output
    .dbg_awid_s0    (                 ),    // output [5:0]
    .dbg_awaddr_s0  (                 ),    // output [31:0]
    .dbg_awlen_s0   (                 ),    // output [7:0]
    .dbg_awsize_s0  (                 ),    // output [2:0]
    .dbg_awburst_s0 (                 ),    // output [1:0]
    .dbg_awlock_s0  (                 ),    // output
    .dbg_awcache_s0 (                 ),    // output [3:0]
    .dbg_awprot_s0  (                 ),    // output [2:0]
    .dbg_awvalid_s0 (                 ),    // output
    .dbg_awready_s0 (                 ),    // output
    .dbg_wid_s0     (                 ),    // output [5:0]
    .dbg_wdata_s0   (                 ),    // output [63:0]
    .dbg_wstrb_s0   (                 ),    // output [7:0]
    .dbg_wlast_s0   (                 ),    // output
    .dbg_wvalid_s0  (                 ),    // output
    .dbg_wready_s0  (                 ),    // output
    .dbg_bid_s0     (                 ),    // output [5:0]
    .dbg_bresp_s0   (                 ),    // output [1:0]
    .dbg_bvalid_s0  (                 ),    // output
    .dbg_bready_s0  (                 ),    // output
    .dbg_arid_s0    (                 ),    // output [5:0]
    .dbg_araddr_s0  (                 ),    // output [31:0]
    .dbg_arlen_s0   (                 ),    // output [7:0]
    .dbg_arsize_s0  (                 ),    // output [2:0]
    .dbg_arburst_s0 (                 ),    // output [1:0]
    .dbg_arlock_s0  (                 ),    // output
    .dbg_arcache_s0 (                 ),    // output [3:0]
    .dbg_arprot_s0  (                 ),    // output [2:0]
    .dbg_arvalid_s0 (                 ),    // output
    .dbg_arready_s0 (                 ),    // output
    .dbg_rid_s0     (                 ),    // output [5:0]
    .dbg_rdata_s0   (                 ),    // output [63:0]
    .dbg_rresp_s0   (                 ),    // output [1:0]
    .dbg_rvalid_s0  (                 ),    // output
    .dbg_rlast_s0   (                 ),    // output
    .dbg_rready_s0  (                 )     // output
);

endmodule