#!/usr/bin/env python3
"""Extract AXKU15 DDR4 pin constraints from the checked-in board manual.

The manual is the single source of truth for this board. The output only
assigns PACKAGE_PIN: a verified MIG configuration owns electrical standards.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


MANUAL = Path(__file__).resolve().parents[2] / "AXKU15_V1.2_UG_final.md"
ROW = re.compile(r"^\|DDR4_([A-Z0-9_]+)\|([A-Z]+[0-9]+)\|$")
MIG_COMMAND_ADDRESS = {"WE_B": 14, "CAS_B": 15, "RAS_B": 16}


def read_pins(manual: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in manual.read_text(encoding="utf-8").splitlines():
        match = ROW.match(line.strip().replace(r"\_", "_"))
        if match:
            name, pin = match.groups()
            if name in pins:
                raise ValueError(f"duplicate DDR4 signal in manual: {name}")
            pins[name] = pin
    required = {f"D{i}" for i in range(80)}
    missing = sorted(required - pins.keys())
    if missing:
        raise ValueError(f"manual is missing DDR4 data pins: {', '.join(missing)}")
    if len({pins[f"D{i}"] for i in range(80)}) != 80:
        raise ValueError("DDR4 DQ package pins are not unique")
    return pins


def _xdc_port(name: str, *, mig_style: bool) -> str:
    base = "c0_ddr4" if mig_style else "ddr4"
    if name.startswith("D") and name[1:].isdigit():
        return f"{base}_dq[{name[1:]}]"
    if name.startswith("DM"):
        return f"{base}_dm_dbi_n[{name[2:]}]"
    if name.startswith("DQS"):
        number, polarity = name[3:].split("_")
        if mig_style:
            return f"{base}_dqs_{'t' if polarity == 'P' else 'c'}[{number}]"
        return f"{base}_dqs_{polarity.lower()}[{number}]"
    if name.startswith("A") and name[1:].isdigit():
        return f"{base}_adr[{name[1:]}]"
    if name in MIG_COMMAND_ADDRESS and mig_style:
        return f"{base}_adr[{MIG_COMMAND_ADDRESS[name]}]"
    if name.startswith("BA"):
        return f"{base}_ba[{name[2:]}]"
    if name == "BG0":
        return f"{base}_bg[0]"
    if name == "CLKREF_P":
        return "c0_sys_clk_p" if mig_style else "ddr4_ref_clk_p"
    if name == "CLKREF_N":
        return "c0_sys_clk_n" if mig_style else "ddr4_ref_clk_n"
    aliases = {
        "ACT_B": f"{base}_act_n", "ALERT_B": f"{base}_alert_n",
        "CAS_B": f"{base}_cas_n", "CKE": f"{base}_cke[0]",
        "CLK_N": f"{base}_ck_c[0]", "CLK_P": f"{base}_ck_t[0]",
        "CS_B": f"{base}_cs_n[0]", "OTD": f"{base}_odt[0]",
        "PAR": f"{base}_parity", "RAS_B": f"{base}_ras_n",
        "RST": f"{base}_reset_n" if mig_style else f"{base}_reset_n[0]",
        "WE_B": f"{base}_we_n",
    }
    return aliases[name]


def render_xdc(pins: dict[str, str], *, data_width: int = 80, mig_style: bool = False) -> str:
    if data_width not in {64, 80}:
        raise ValueError("data width must be either 64 or 80")
    ordered = [f"D{i}" for i in range(data_width)]
    ordered += [f"DM{i}" for i in range(data_width // 8)]
    for index in range(data_width // 8):
        ordered += [f"DQS{index}_P", f"DQS{index}_N"]
    controls = [
        "OTD", "PAR", "RAS_B", "RST", "WE_B", *(f"A{i}" for i in range(14)),
        "ACT_B", "ALERT_B", "BA0", "BA1", "BG0", "CAS_B", "CKE", "CLK_N",
        "CLK_P", "CS_B", "CLKREF_P", "CLKREF_N",
    ]
    # The generated MIG candidate has parity disabled, so it exposes neither
    # the input PAR nor the output ALERT_n. RAS/CAS/WE use A[16:14] instead.
    if mig_style:
        controls = [name for name in controls if name not in {"PAR", "ALERT_B"}]
    ordered += controls
    missing = [name for name in ordered if name not in pins]
    if missing:
        raise ValueError(f"manual is missing DDR4 control pins: {', '.join(missing)}")
    ref_clock = _xdc_port("CLKREF_P", mig_style=mig_style)
    lines = [
        "# Generated by scripts/extract_ddr4_pins.py; do not edit by hand.",
        "# Source: ../AXKU15_V1.2_UG_final.md (DDR4 SDRAM pin table).",
        "# Apply only after validating the associated DDR4 controller configuration.",
        f"create_clock -name ddr4_ref_clk -period 5.000 [get_ports {ref_clock}]",
    ]
    lines.extend(
        f"set_property PACKAGE_PIN {pins[name]} [get_ports {{{_xdc_port(name, mig_style=mig_style)}}}]"
        for name in ordered
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manual", type=Path, default=MANUAL)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--data-width", type=int, choices=(64, 80), default=80)
    parser.add_argument("--format", choices=("generic", "mig"), default="generic")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_xdc(read_pins(args.manual), data_width=args.data_width, mig_style=args.format == "mig"),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()