#!/usr/bin/env python3
"""Extract AXKU15 DDR4 pin constraints from the checked-in board manual.

The manual is the single source of truth for this board.  The output only
assigns PACKAGE_PIN: MIG owns the electrical standards and termination rules.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


MANUAL = Path(__file__).resolve().parents[2] / "AXKU15_V1.2_UG_final.md"
ROW = re.compile(r"^\|DDR4_([A-Z0-9_]+)\|([A-Z]+[0-9]+)\|$")


def read_pins(manual: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in manual.read_text(encoding="utf-8").splitlines():
        match = ROW.match(line.strip().replace(r"\_", "_"))
        if match:
            name, pin = match.groups()
            if name in pins:
                raise ValueError(f"duplicate DDR4 signal in manual: {name}")
            pins[name] = pin
    required = {f"D{i}" for i in range(80)}
    missing = sorted(required - pins.keys())
    if missing:
        raise ValueError(f"manual is missing DDR4 data pins: {', '.join(missing)}")
    if len({pins[f"D{i}"] for i in range(80)}) != 80:
        raise ValueError("DDR4 DQ package pins are not unique")
    return pins


def _xdc_port(name: str) -> str:
    if name.startswith("D") and name[1:].isdigit():
        return f"ddr4_dq[{name[1:]}]"
    if name.startswith("DM"):
        return f"ddr4_dm_dbi_n[{name[2:]}]"
    if name.startswith("DQS"):
        number, polarity = name[3:].split("_")
        return f"ddr4_dqs_{polarity.lower()}[{number}]"
    if name.startswith("A") and name[1:].isdigit():
        return f"ddr4_adr[{name[1:]}]"
    if name.startswith("BA"):
        return f"ddr4_ba[{name[2:]}]"
    if name == "BG0":
        return "ddr4_bg[0]"
    aliases = {
        "ACT_B": "ddr4_act_n", "ALERT_B": "ddr4_alert_n", "CAS_B": "ddr4_cas_n",
        "CKE": "ddr4_cke[0]", "CLK_N": "ddr4_ck_c[0]", "CLK_P": "ddr4_ck_t[0]",
        "CS_B": "ddr4_cs_n[0]", "CLKREF_N": "ddr4_ref_clk_n", "CLKREF_P": "ddr4_ref_clk_p", "OTD": "ddr4_odt[0]", "PAR": "ddr4_parity",
        "RAS_B": "ddr4_ras_n", "RST": "ddr4_reset_n[0]", "WE_B": "ddr4_we_n",
    }
    if name in aliases:
        return aliases[name]
    return "ddr4_" + name.lower().replace("_b", "_n")


def render_xdc(pins: dict[str, str]) -> str:
    ordered = [f"D{i}" for i in range(80)]
    ordered += [f"DM{i}" for i in range(10)]
    for index in range(10):
        ordered += [f"DQS{index}_P", f"DQS{index}_N"]
    ordered += [
        "OTD", "PAR", "RAS_B", "RST", "WE_B", *(f"A{i}" for i in range(14)),
        "ACT_B", "ALERT_B", "BA0", "BA1", "BG0", "CAS_B", "CKE", "CLK_N",
        "CLK_P", "CS_B", "CLKREF_P", "CLKREF_N",
    ]
    missing = [name for name in ordered if name not in pins]
    if missing:
        raise ValueError(f"manual is missing DDR4 control pins: {', '.join(missing)}")
    lines = [
        "# Generated by scripts/extract_ddr4_pins.py; do not edit by hand.",
        "# Source: ../AXKU15_V1.2_UG_final.md (DDR4 SDRAM pin table).",
        "# Apply this together with a Vivado DDR4 MIG generated for this exact board.",
        "create_clock -name ddr4_ref_clk -period 5.000 [get_ports ddr4_ref_clk_p]",
    ]
    lines.extend(
        f"set_property PACKAGE_PIN {pins[name]} [get_ports {{{_xdc_port(name)}}}]"
        for name in ordered
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manual", type=Path, default=MANUAL)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_xdc(read_pins(args.manual)), encoding="utf-8")


if __name__ == "__main__":
    main()
